# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Desert Drift Team
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ddtdriftteam@gmail.com
facebook_username: https://www.facebook.com/groups/327586277723124
twitter_username: /
instagram_username: desertdriftteam.ddt
linkedin_username: /
github_username: /
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: DDT
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: Welcome to Albuquerque RC Drifters!

Are you passionate about the thrill of precision driving and the artistry of controlled slides? Look no further! Join our tight-knit community of RC drift enthusiasts right here in Albuquerque. Whether you're a seasoned pro or just getting started, our group is all about fostering a fun and supportive environment where we can share tips, tricks, and of course, the sheer joy of drifting.

🛠️ What We're About:

Passion for Drifting: We eat, sleep, and breathe RC drifting. It's not just a hobby; it's a way of life.
Skill Development: Whether you're honing your technique or learning the basics, we're here to help each other improve and grow as drivers.
Community Connection: From casual meetups to intense competitions, we're all about forging friendships and building camaraderie among fellow drift enthusiasts.
Respect and Sportsmanship: We believe in fair play, mutual respect, and encouraging each other's progress. No egos allowed—just good vibes and positive energy.
🏁 What We Do:

Weekly Meetups: Join us for our regular gatherings at various drift spots across Albuquerque. It's the perfect opportunity to practice, socialize, and learn from one another.
Workshops and Clinics: From tuning your setup to perfecting your technique, our group hosts workshops and clinics to help you level up your drifting game.
Competitions and Events: Get ready to put your skills to the test! We organize friendly competitions and attend events to showcase our drifting prowess and represent Albuquerque's RC drift scene.
🤝 Join Us Today!
Whether you're a seasoned veteran or a curious newcomer, there's a place for you in our Albuquerque RC Drifters family. Come drift with us and experience the adrenaline rush of sideways action like never before! Join our group and let's hit the track together. See you at the next drift session! 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
